# Generated by Django 5.1.7 on 2025-03-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_booking_id_alter_menu_menu_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='inventory',
            field=models.IntegerField(),
        ),
    ]
